Alex Albaugh.  Wayne State.  CHE 5995/7507.  Lecture 4.  Winter 2026.

<code>Numpy</code> provides an array (ha!) of built in tools for doing linear algebra.  We'll go through some examples here.

In [ ]:
import numpy as np

First, <code>numpy</code> comes with its own arrarys, using <code>np.array</code>.  These arrays are similar to standard <code>Python</code> lists, but some of their behavior is modified.  The biggest changes are under the hood.  While standard <code>Python</code> lists are general purpose, <code>numpy</code> arrarys are built to be optimized for fast computations.  Think of <code>Python</code> lists as an all-purpose van and <code>numpy</code> arrays as a specialized race car.

In [ ]:
#numpy vector
v = np.array([1.2, -3.4, 4.6])
print(v)

[ 1.2 -3.4  4.6]


In [ ]:
#dimensions of vector
print(v.ndim)

#size of vector
print(v.size)

#shape of vector
print(v.shape)

1
3
(3,)


We can access elements of the vector with an index that starts at 0 and goes to the size of the array - 1.

In [ ]:
print(v[0])
print(v[1])
print(v[2])

1.2
-3.4
4.6


We can a subset of elements with a slice.

In [ ]:
v = np.arange(0,9,1)
N = 3

#get the first N elements of the vector
print(v[:N])

#get the elements from N+1 to the end of the vector
print(v[N:])

#get a range of elements
print(v[3:6])

[0 1 2]
[3 4 5 6 7 8]
[3 4 5]


Matrices are then arrarys of arrarys that form a 2D table.

In [ ]:
M = np.array([[4.3, -1.8, -2.1], [-3.0, 5.6, 1.3], [0.6, 2.1, 1.9]])
print(M)

[[ 4.3 -1.8 -2.1]
 [-3.   5.6  1.3]
 [ 0.6  2.1  1.9]]


In [ ]:
#dimensions of matrix
print(M.ndim)

#size of matrix
print(M.size)

#shape of matrix
print(M.shape)

2
9
(3, 3)


We can access elements of the matrix with two indices.  The first index specifies the row, the second specifies the column.

In [ ]:
print(M[0][0])
print(M[1][2])
print(M[2][0])

4.3
1.3
0.6


In [ ]:
#the above is equivalent to:
print(M[0,0])
print(M[1,2])
print(M[2,0])

4.3
1.3
0.6


We can use slices to access specific rows and columns.

In [ ]:
#get the second column of the matrix
print(M[:,1])

#get the second row of the matrix
print(M[1,:])

[-1.8  5.6  2.1]
[-3.   5.6  1.3]


We can quickly build a matrix of zeros of a specified size with <code>np.zeros</code>.  We can quickly build an identity matrix with <code>np.eye</code>.

In [ ]:
#build a 3x4 matrix of 0
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#build a 5x5 identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


We can do element-wise addition and subtraction if our <code>numpy</code> arrays are the same shape.

In [ ]:
v = np.array([1, 2])
w = np.array([3, 4])
print(v+w)

A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
print(A-B)

[4 6]
[[-3 -1]
 [ 1  3]]


We can also do scalar multiplication.

In [ ]:
v = np.array([1, 2])
c = 12
print(c*v)

A = np.array([[1,2],[3,4]])
c = -1
print(c*A)

[12 24]
[[-1 -2]
 [-3 -4]]


Transpose is done with <code>.T</code>.

In [ ]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


We can do the dot product with <code>np.dot</code>.  For this, vectors must be the same size.

In [ ]:
v = np.array([1, 2])
w = np.array([3, 4])
print(np.dot(v,w))

11


We can get the length or $l_2$-norm of a vector directly with <code>np.linalg.norm</code>.

---



In [ ]:
v = np.array([1, 2])
print(np.linalg.norm(v))

2.23606797749979


We can do matrix-vector multiplication with either <code>dot</code> or <code>matmul</code>.

In [ ]:
A = np.array([[1,2],[3,4]])
v = np.array([1, 2])
print(np.dot(A,v))

#equivalent to...
print(np.matmul(A,v))

[ 5 11]
[ 5 11]


Matrix multiplication, then, is done with <code>matmul</code>.  The number of columns of the first matrix must be equal to the number of rows of the second matrix.

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
print(np.matmul(A,B))

[[ 8  5]
 [20 13]]


We can use <code>@</code> as shorthand for matrix multiplication.

In [ ]:
v = np.array([1, 2])
w = np.array([3, 4])
print(v @ w)

A = np.array([[1,2],[3,4]])
v = np.array([1, 2])
print(A @ v)

A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
print(A @ B)

11
[ 5 11]
[[ 8  5]
 [20 13]]


With <code>numpy</code>'s built-in functions we can easily calculate the determinant and trace of a matrix.

In [ ]:
A = np.array([[1,2],[3,4]])

print('Determinant: ', np.linalg.det(A))

print('Trace: ', np.trace(A))

Determinant:  -2.0000000000000004
Trace:  5


We can also easily get the inverse of a matrix.

In [ ]:
A = np.array([[1,2],[3,4]])

Ainv = np.linalg.inv(A)

print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#check that this is the inverse, this should an identity matrix
print(Ainv @ A)

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


We can get the eigenvalues and vectors with <code>linalg.eig</code>.  The first returned value is a 1-D array of the eigenvalues.  The second returned value is a matrix where the each column is an eigenvector.

In [ ]:
A = np.array([[1,2],[3,4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print('First eigenvalue: ', eigenvalues[0])
print('First eigenvector: ', eigenvectors[:,0])

#let's test this, the following should give a zero vector
print(A @ eigenvectors[:,0] - eigenvalues[0]*eigenvectors[:,0])

print('Second eigenvalue: ', eigenvalues[1])
print('Second eigenvector: ', eigenvectors[:,1])

#let's test this, the following should give a zero vector
print(A @ eigenvectors[:,1] - eigenvalues[1]*eigenvectors[:,1])

#numpy eigenvectors are always normalized to have length 1
print('First eigenvector l2-norm: ', np.linalg.norm(eigenvectors[:,0]))
print('Second eigenvector l2-norm: ', np.linalg.norm(eigenvectors[:,1]))

First eigenvalue:  -0.3722813232690143
First eigenvector:  [-0.82456484  0.56576746]
[ 0.00000000e+00 -5.55111512e-17]
Second eigenvalue:  5.372281323269014
Second eigenvector:  [-0.41597356 -0.90937671]
[-4.4408921e-16  0.0000000e+00]
First eigenvector l2-norm:  1.0
Second eigenvector l2-norm:  1.0
